name: Build Application

on:
  pull_request:
    types: [closed]
    branches: [main]
jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Build Application
    uses: ./.github/workflows/build-reusable.yml
